baseURL = "https://freesoftwarelab.noi.bz.it/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Free Software Lab"
theme = "free-software-lab"
googleAnalytics = "UA-153698977-1"


[imaging]
resampleFilter = "box"
quality = 10


[languages.en]
weight = 0
languageName = "English"
contentDir = "content/en"

[[languages.en.menu.main]]
url    = "/"
name   = "Home"
weight = 0

[[languages.en.menu.main]]
url    = "/services"
name   = "Services"
weight = 10

# [[languages.en.menu.main]]
#url    = "/testenv"
#name   = "Test Environment"
#weight = 20

[[languages.en.menu.main]]
url    = "/observatory"
name   = "Observatory"
weight = 30

[[languages.en.menu.main]]
url    = "/contact"
name   = "Contact"
weight = 40

[languages.de]
weight = 10
contentDir = "content/de/"
languageName = "Deutsch"

[[languages.de.menu.main]]
url    = "/"
name   = "Home"
weight = 0

[[languages.de.menu.main]]
url    = "/services"
name   = "Dienstleitungen"
weight = 10

[[languages.de.menu.main]]
url    = "/contact"
name   = "Kontakt"
weight = 20

[languages.it]
weight = 20
contentDir = "content/it/"
languageName = "Italiano"

[[languages.it.menu.main]]
url    = "/"
name   = "Home"
weight = 0

[[languages.it.menu.main]]
url    = "services"
name   = "Servizi"
weight = 10

[[languages.it.menu.main]]
url    = "/contact"
name   = "Contatto"
weight = 20

[[languages.en.menu.footer]]
url    = "https://noi.bz.it/privacy-cookie-policy"
name   = "Privacy"
weight = 10

[[languages.en.menu.footer]]
url    = "https://noi.bz.it/privacy-cookie-policy"
name   = "Cookies"
weight = 20

[[languages.en.menu.footer]]
url    = "/contact"
name   = "Contact"
weight = 30

[[languages.de.menu.footer]]
url    = "https://noi.bz.it/privacy-cookie-policy"
name   = "Privacy"
weight = 10

[[languages.de.menu.footer]]
url    = "https://noi.bz.it/privacy-cookie-policy"
name   = "Cookies"
weight = 20

[[languages.de.menu.footer]]
url    = "/contact"
name   = "Kontakt"
weight = 30

[[languages.it.menu.footer]]
url    = "https://noi.bz.it/privacy-cookie-policy"
name   = "Privacy"
weight = 10

[[languages.it.menu.footer]]
url    = "https://noi.bz.it/privacy-cookie-policy"
name   = "Cookies"
weight = 20

[[languages.it.menu.footer]]
url    = "/contact"
name   = "Contatto"
weight = 30
